<?php

/**
 * Implements hook_menu
 */
function menufun_menu() {
  $items['menufun'] = [
    'title' => 'Menu Fun',
    'page callback' => 'menufun_greeting',
    'file' => 'menufun_greeting.inc',
    'page arguments' => array('Jane', 'Doe'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
    'weight' => -1,
  ];
  
  $items['menufun/farewell'] = [
    'title' => 'Farewell',
    'page callback' => 'menufun_farewell',
    'file' => 'menufun_greeting.inc',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  ];
      
  return $items;
}

function menufun_hello($first_name = '', $last_name = '') {
  return t('Hello @first_name @last_name', array('@first_name' => $first_name, '@last_name' => $last_name));
}